# Sample configuration file for a project
---
# Define the names of gems that the server needs to require
# These have to be gems that are included in the bundle otherwise they will not load
required_libs:
    - em-mongo 

# Define whether or not to use a logfile
logfile: server.log 

# Port the server should listen on. Android clients must connect to the same port.
port: 8080

# Are binary files being passed as Base64? Values are true or false
binary_base64: true

# These fields determine if a client must send an id and timestamp with each message. Disabling either of these options disables the server validation.
require_id: true
require_timestamp: true

# Uncomment the next line and list any additional files to load here
#required_files:
